apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: springboot
  name: springboot
spec:
  ports:
  - port: 8070
    protocol: TCP
    targetPort: 8070
  selector:
    run: springboot
  type: NodePort
status:
  loadBalancer: {}
